name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: mvn compile

      - name: Test
        run: mvn test

      - name: Package JAR
        run: mvn package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar